[tool.poetry]
authors = ["Allen Chou <f1470891079@gmail.com>"]
description = "A bullet-train style Python logging utils."
license = "MIT"
name = "logging-bullet-train"
packages = [{ include = "logging_bullet_train" }]
readme = "README.md"
version = "0.4.0"

[tool.poetry.dependencies]
colorama = "*"
python = ">=3.11,<4.0"

[tool.poetry.extras]
all = []

[tool.poetry.group.dev.dependencies]
black = { extras = ["jupyter"], version = "*" }
mkdocs-git-authors-plugin = "*"
mkdocs-git-committers-plugin-2 = "*"
mkdocs-git-revision-date-localized-plugin = "*"
mkdocs-material = "*"
mkdocs-minify-plugin = "*"
mkdocs-nav-weight = "*"
mkdocs-redirects = "*"
mkdocs-render-swagger-plugin = "*"
neoteroi-mkdocs = "*"
poetry-plugin-export = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-xdist = "*"
setuptools = ">=69"

[tool.isort]
profile = "black"

[tool.flake8]
ignore = ["E203", "E704", "W503"]
max-line-length = 88

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
