"""Emoji themes for bullet-train log levels."""

import logging
import typing

LOGGING_UNKNOWN = 1
Theme: typing.TypeAlias = dict[int, str]

level_emoji_default: Theme = {
    logging.DEBUG: "🔎",
    logging.INFO: "💡",
    logging.WARNING: "⭐",
    logging.ERROR: "🚨",
    logging.CRITICAL: "🔥",
    LOGGING_UNKNOWN: "🔘",
}
level_emoji_fruit: Theme = {
    logging.DEBUG: "🫐",
    logging.INFO: "🍏",
    logging.WARNING: "🍋",
    logging.ERROR: "🍒",
    logging.CRITICAL: "🌶️",
    LOGGING_UNKNOWN: "🍇",
}
level_emoji_weather: Theme = {
    logging.DEBUG: "🌤️",
    logging.INFO: "☀️",
    logging.WARNING: "🌦️",
    logging.ERROR: "⛈️",
    logging.CRITICAL: "🌪️",
    LOGGING_UNKNOWN: "🌈",
}
level_emoji_night: Theme = {
    logging.DEBUG: "🌑",
    logging.INFO: "🌓",
    logging.WARNING: "🌕",
    logging.ERROR: "🌠",
    logging.CRITICAL: "☄️",
    LOGGING_UNKNOWN: "🌌",
}

level_emojis: dict[str, Theme] = {
    "default": level_emoji_default,
    "fruit": level_emoji_fruit,
    "weather": level_emoji_weather,
    "night": level_emoji_night,
    "classic": {
        logging.DEBUG: "🛠️",
        logging.INFO: "ℹ️",
        logging.WARNING: "⚠️",
        logging.ERROR: "❌",
        logging.CRITICAL: "💥",
        LOGGING_UNKNOWN: "❔",
    },
    "minimal": {
        logging.DEBUG: "·",
        logging.INFO: "i",
        logging.WARNING: "!",
        logging.ERROR: "x",
        logging.CRITICAL: "X",
        LOGGING_UNKNOWN: "?",
    },
    "symbols": {
        logging.DEBUG: "◇",
        logging.INFO: "◆",
        logging.WARNING: "▲",
        logging.ERROR: "■",
        logging.CRITICAL: "⬢",
        LOGGING_UNKNOWN: "○",
    },
    "shapes": {
        logging.DEBUG: "○",
        logging.INFO: "●",
        logging.WARNING: "△",
        logging.ERROR: "□",
        logging.CRITICAL: "◆",
        LOGGING_UNKNOWN: "◇",
    },
    "status": {
        logging.DEBUG: "🔧",
        logging.INFO: "✅",
        logging.WARNING: "⚠️",
        logging.ERROR: "⛔",
        logging.CRITICAL: "🆘",
        LOGGING_UNKNOWN: "❓",
    },
    "traffic": {
        logging.DEBUG: "🚲",
        logging.INFO: "🟢",
        logging.WARNING: "🟡",
        logging.ERROR: "🔴",
        logging.CRITICAL: "🚧",
        LOGGING_UNKNOWN: "⚪",
    },
    "space": {
        logging.DEBUG: "🛰️",
        logging.INFO: "🌎",
        logging.WARNING: "🪐",
        logging.ERROR: "☄️",
        logging.CRITICAL: "🚀",
        LOGGING_UNKNOWN: "✨",
    },
    "fire": {
        logging.DEBUG: "🕯️",
        logging.INFO: "🔥",
        logging.WARNING: "♨️",
        logging.ERROR: "🚒",
        logging.CRITICAL: "💥",
        LOGGING_UNKNOWN: "🌫️",
    },
    "ocean": {
        logging.DEBUG: "🫧",
        logging.INFO: "🌊",
        logging.WARNING: "🛟",
        logging.ERROR: "⚓",
        logging.CRITICAL: "🌀",
        LOGGING_UNKNOWN: "💧",
    },
    "garden": {
        logging.DEBUG: "🌱",
        logging.INFO: "🌿",
        logging.WARNING: "🌻",
        logging.ERROR: "🥀",
        logging.CRITICAL: "🌋",
        LOGGING_UNKNOWN: "🍃",
    },
    "coffee": {
        logging.DEBUG: "☕",
        logging.INFO: "🥛",
        logging.WARNING: "🫖",
        logging.ERROR: "🧯",
        logging.CRITICAL: "🔥",
        LOGGING_UNKNOWN: "🥄",
    },
    "terminal": {
        logging.DEBUG: ">",
        logging.INFO: "$",
        logging.WARNING: "!",
        logging.ERROR: "!!",
        logging.CRITICAL: "!!!",
        LOGGING_UNKNOWN: "?",
    },
    "build": {
        logging.DEBUG: "🧪",
        logging.INFO: "📦",
        logging.WARNING: "🔨",
        logging.ERROR: "🧱",
        logging.CRITICAL: "🏗️",
        LOGGING_UNKNOWN: "📎",
    },
    "security": {
        logging.DEBUG: "🔍",
        logging.INFO: "🔐",
        logging.WARNING: "🛡️",
        logging.ERROR: "🚫",
        logging.CRITICAL: "🚨",
        LOGGING_UNKNOWN: "🔑",
    },
    "data": {
        logging.DEBUG: "🔬",
        logging.INFO: "📊",
        logging.WARNING: "📈",
        logging.ERROR: "📉",
        logging.CRITICAL: "🧨",
        LOGGING_UNKNOWN: "🗂️",
    },
    "rocket": {
        logging.DEBUG: "🛠️",
        logging.INFO: "🚄",
        logging.WARNING: "🚦",
        logging.ERROR: "🛑",
        logging.CRITICAL: "🚀",
        LOGGING_UNKNOWN: "🧭",
    },
    "office": {
        logging.DEBUG: "📝",
        logging.INFO: "📌",
        logging.WARNING: "📎",
        logging.ERROR: "📍",
        logging.CRITICAL: "📣",
        LOGGING_UNKNOWN: "📄",
    },
    "database": {
        logging.DEBUG: "🔎",
        logging.INFO: "💾",
        logging.WARNING: "🧮",
        logging.ERROR: "🗃️",
        logging.CRITICAL: "🧨",
        LOGGING_UNKNOWN: "🧾",
    },
    "cloud": {
        logging.DEBUG: "☁️",
        logging.INFO: "🌤️",
        logging.WARNING: "🌥️",
        logging.ERROR: "🌧️",
        logging.CRITICAL: "🌩️",
        LOGGING_UNKNOWN: "🌫️",
    },
    "music": {
        logging.DEBUG: "🎚️",
        logging.INFO: "🎵",
        logging.WARNING: "🎧",
        logging.ERROR: "🎙️",
        logging.CRITICAL: "🔊",
        LOGGING_UNKNOWN: "🎼",
    },
    "kitchen": {
        logging.DEBUG: "🔪",
        logging.INFO: "🍽️",
        logging.WARNING: "🥣",
        logging.ERROR: "🧂",
        logging.CRITICAL: "🔥",
        LOGGING_UNKNOWN: "🥄",
    },
    "sports": {
        logging.DEBUG: "🎯",
        logging.INFO: "🏁",
        logging.WARNING: "🥈",
        logging.ERROR: "🥊",
        logging.CRITICAL: "🏆",
        LOGGING_UNKNOWN: "🎟️",
    },
    "health": {
        logging.DEBUG: "🩺",
        logging.INFO: "💚",
        logging.WARNING: "🩹",
        logging.ERROR: "💊",
        logging.CRITICAL: "🚑",
        LOGGING_UNKNOWN: "🧬",
    },
    "money": {
        logging.DEBUG: "🧾",
        logging.INFO: "💵",
        logging.WARNING: "💳",
        logging.ERROR: "💸",
        logging.CRITICAL: "🏦",
        LOGGING_UNKNOWN: "🪙",
    },
    "time": {
        logging.DEBUG: "⏱️",
        logging.INFO: "🕒",
        logging.WARNING: "⏳",
        logging.ERROR: "⌛",
        logging.CRITICAL: "⏰",
        LOGGING_UNKNOWN: "🗓️",
    },
    "navigation": {
        logging.DEBUG: "🧭",
        logging.INFO: "🗺️",
        logging.WARNING: "🚦",
        logging.ERROR: "⛔",
        logging.CRITICAL: "🛑",
        LOGGING_UNKNOWN: "📍",
    },
    "signal": {
        logging.DEBUG: "📡",
        logging.INFO: "📶",
        logging.WARNING: "⚡",
        logging.ERROR: "📵",
        logging.CRITICAL: "🚨",
        LOGGING_UNKNOWN: "〰️",
    },
    "battery": {
        logging.DEBUG: "🪫",
        logging.INFO: "🔋",
        logging.WARNING: "🟨",
        logging.ERROR: "🟥",
        logging.CRITICAL: "⚡",
        LOGGING_UNKNOWN: "⬜",
    },
    "mail": {
        logging.DEBUG: "✉️",
        logging.INFO: "📨",
        logging.WARNING: "📬",
        logging.ERROR: "📭",
        logging.CRITICAL: "📢",
        LOGGING_UNKNOWN: "📮",
    },
    "docs": {
        logging.DEBUG: "🔖",
        logging.INFO: "📘",
        logging.WARNING: "📙",
        logging.ERROR: "📕",
        logging.CRITICAL: "📚",
        LOGGING_UNKNOWN: "📃",
    },
    "science": {
        logging.DEBUG: "🔬",
        logging.INFO: "🧪",
        logging.WARNING: "⚗️",
        logging.ERROR: "🧫",
        logging.CRITICAL: "☢️",
        LOGGING_UNKNOWN: "🧲",
    },
    "education": {
        logging.DEBUG: "✏️",
        logging.INFO: "📗",
        logging.WARNING: "📐",
        logging.ERROR: "🧯",
        logging.CRITICAL: "🎓",
        LOGGING_UNKNOWN: "📓",
    },
    "festival": {
        logging.DEBUG: "🎈",
        logging.INFO: "🎉",
        logging.WARNING: "🎭",
        logging.ERROR: "🎇",
        logging.CRITICAL: "🎆",
        LOGGING_UNKNOWN: "🎫",
    },
    "travel": {
        logging.DEBUG: "🧳",
        logging.INFO: "🚆",
        logging.WARNING: "🚏",
        logging.ERROR: "🛂",
        logging.CRITICAL: "✈️",
        LOGGING_UNKNOWN: "🛎️",
    },
    "control": {
        logging.DEBUG: "🎛️",
        logging.INFO: "✅",
        logging.WARNING: "🟧",
        logging.ERROR: "🟥",
        logging.CRITICAL: "🔴",
        LOGGING_UNKNOWN: "⚙️",
    },
    "faces": {
        logging.DEBUG: "🤔",
        logging.INFO: "🙂",
        logging.WARNING: "😬",
        logging.ERROR: "😵",
        logging.CRITICAL: "😱",
        LOGGING_UNKNOWN: "😶",
    },
    "hands": {
        logging.DEBUG: "👈",
        logging.INFO: "👍",
        logging.WARNING: "☝️",
        logging.ERROR: "👎",
        logging.CRITICAL: "🫸",
        LOGGING_UNKNOWN: "🤌",
    },
    "tools": {
        logging.DEBUG: "🔧",
        logging.INFO: "⚙️",
        logging.WARNING: "🪛",
        logging.ERROR: "🔩",
        logging.CRITICAL: "🧰",
        LOGGING_UNKNOWN: "📏",
    },
    "cards": {
        logging.DEBUG: "♣️",
        logging.INFO: "♦️",
        logging.WARNING: "♥️",
        logging.ERROR: "♠️",
        logging.CRITICAL: "🃏",
        LOGGING_UNKNOWN: "🎴",
    },
    "medical": {
        logging.DEBUG: "🧬",
        logging.INFO: "💉",
        logging.WARNING: "🩹",
        logging.ERROR: "🩻",
        logging.CRITICAL: "🏥",
        LOGGING_UNKNOWN: "⚕️",
    },
    "plain": {
        logging.DEBUG: "DEBUG",
        logging.INFO: "INFO",
        logging.WARNING: "WARN",
        logging.ERROR: "ERROR",
        logging.CRITICAL: "CRIT",
        LOGGING_UNKNOWN: "UNK",
    },
}


def get_theme(theme: str | Theme = "default") -> Theme:
    """Return a complete emoji theme by name or mapping."""
    if isinstance(theme, str):
        try:
            return level_emojis[theme]
        except KeyError as error:
            available = ", ".join(sorted(level_emojis))
            raise ValueError(
                f"unknown theme {theme!r}; choose one of: {available}"
            ) from error

    return {**level_emoji_default, **theme}
